### ISSUE TITLE
idp initiated sign out fail

### ISSUE THREAD

**Issue by wintercomic** [onelogin/php-saml#136]
Hello,

I try to use onelogin php-saml toolkit (as SP) to test with our ADFS 3.0 (as IDP). Currently I can get SSO and SP-initiated sign out work, but I have in trouble with IDP-initiated sign out.

I try to logout in ADFS, the request can work fine, I can successful logout in toolkit. but the Response is getting rejected by ADFS. I get the following error in ADFS side.

> The Federation Service encountered an error while processing the SAML authentication request. 
> 
> Additional Data 
> Exception details: 
> Microsoft.IdentityModel.Protocols.XmlSignature.SignatureVerificationFailedException: MSIS0038: SAML Message has wrong signature. Issuer: 'https://xxxxxxxxxx/php-saml/sp'.
>    at Microsoft.IdentityServer.Protocols.Saml.Contract.SamlContractUtility.CreateSamlMessage(MSISSamlBindingMessage message)
>    at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolManager.Logout(HttpSamlMessage logoutMessage, String sessionState, String logoutState, Boolean partialLogout, Boolean isUrlTranslationNeeded, HttpSamlMessage& newLogoutMessage, String& newSessionState, String& newLogoutState, Boolean& validLogoutRequest)

I have no idea why it will show this error, SSO and SP initiated works fine.

Here is the configuration:
settings.php, I place the cert and key in certs folder.

```
<?php
$settings = array (
    // If 'strict' is True, then the PHP Toolkit will reject unsigned
    // or unencrypted messages if it expects them signed or encrypted
    // Also will reject the messages if not strictly follow the SAML
    // standard: Destination, NameId, Conditions ... are validated too.
    'strict' => false,

    // Enable debug mode (to print errors)
    'debug' => true,

    // Service Provider Data that we are deploying
    'sp' => array (
        // Identifier of the SP entity  (must be a URI)
        'entityId' => 'https://xxxxx/php-saml/sp',
        // Specifies info about where and how the <AuthnResponse> message MUST be
        // returned to the requester, in this case our SP.
        'assertionConsumerService' => array (
            // URL Location where the <Response> from the IdP will be returned
            'url' => 'https://xxxxx/php-saml/index.php?acs',
            // SAML protocol binding to be used when returning the <Response>
            // message.  Onelogin Toolkit supports for this endpoint the
            // HTTP-Redirect binding only
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        ),
        // Specifies info about where and how the <Logout Response> message MUST be
        // returned to the requester, in this case our SP.
        'singleLogoutService' => array (
            // URL Location where the <Response> from the IdP will be returned
            'url' => 'https://xxxxx/php-saml/index.php?sls',
            // SAML protocol binding to be used when returning the <Response>
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',

        // Usually x509cert and privateKey of the SP are provided by files placed at
        // the certs folder. But we can also provide them with the following parameters
        'x509cert' => '',
        'privateKey' => '',
    ),

    // Identity Provider Data that we want connect with our SP
    'idp' => array (
        // Identifier of the IdP entity  (must be a URI)
        'entityId' => 'http://xxxxxxxxxx/adfs/services/trust',
        // SSO endpoint info of the IdP. (Authentication Request protocol)
        'singleSignOnService' => array (
            // URL Target of the IdP where the SP will send the Authentication Request Message
            'url' => 'https://xxxxxxxxxxx/adfs/ls/',
            // SAML protocol binding to be used when returning the <Response>
            // message.  Onelogin Toolkit supports for this endpoint the
            // HTTP-POST binding only
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ),
        // SLO endpoint info of the IdP.
        'singleLogoutService' => array (
            // URL Location of the IdP where the SP will send the SLO Request
            'url' => 'https://xxxxxxxxxx/adfs/ls/',
            // SAML protocol binding to be used when returning the <Response>
            // message.  Onelogin Toolkit supports for this endpoint the
            // HTTP-Redirect binding only
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ),
        // Public x509 certificate of the IdP
        'x509cert' => 'MIICxxxxxxxxxxxxpQw==',
        /*
         *  Instead of use the whole x509cert you can use a fingerprint
         *  (openssl x509 -noout -fingerprint -in "idp.crt" to generate it,
         *   or add for example the -sha256 , -sha384 or -sha512 parameter)
         *
         *  If a fingerprint is provided, then the certFingerprintAlgorithm is required in order to
         *  let the toolkit know which Algorithm was used. Possible values: sha1, sha256, sha384 or sha512
         *  'sha1' is the default value.
         */
        // 'certFingerprint' => '',
        // 'certFingerprintAlgorithm' => 'sha1',
    ),
);
```

advanced_settings.php

```
<?php

$advancedSettings = array (

    // Security settings
    'security' => array (

        /** signatures and encryptions offered */

        // Indicates that the nameID of the <samlp:logoutRequest> sent by this SP
        // will be encrypted.
        'nameIdEncrypted' => false,

        // Indicates whether the <samlp:AuthnRequest> messages sent by this SP
        // will be signed.              [The Metadata of the SP will offer this info]
        'authnRequestsSigned' => false,
        'logoutRequestSigned' => true,

        // Indicates whether the <samlp:logoutResponse> messages sent by this SP
        // will be signed.
        'logoutResponseSigned' => true,

        /* Sign the Metadata
         False || True (use sp certs) || array (
                                                    keyFileName => 'metadata.key',
                                                    certFileName => 'metadata.crt'
                                                )
        */
        'signMetadata' => false,


        /** signatures and encryptions required **/

        // Indicates a requirement for the <samlp:Response>, <samlp:LogoutRequest> and
        // <samlp:LogoutResponse> elements received by this SP to be signed.
        'wantMessagesSigned' => false,

        // Indicates a requirement for the <saml:Assertion> elements received by
        // this SP to be signed.        [The Metadata of the SP will offer this info]
        'wantAssertionsSigned' => false,

        // Indicates a requirement for the NameID element on the SAMLResponse received
        // by this SP to be present.
        'wantNameId' => true,

        // Indicates a requirement for the NameID received by
        // this SP to be encrypted.
        'wantNameIdEncrypted' => false,

        // Authentication context.
        // Set to false and no AuthContext will be sent in the AuthNRequest,
        'requestedAuthnContext' => false,

        // Allows the authn comparison parameter to be set, defaults to 'exact' if
        // the setting is not present.
        'requestedAuthnContextComparison' => 'exact',

        // Indicates if the SP will validate all received xmls.
        // (In order to validate the xml, 'strict' and 'wantXMLValidation' must be true).
        'wantXMLValidation' => true,

        // Algorithm that the toolkit will use on signing process. Options:
        //    'http://www.w3.org/2000/09/xmldsig#rsa-sha1'
        //    'http://www.w3.org/2000/09/xmldsig#dsa-sha1'
        //    'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        //    'http://www.w3.org/2001/04/xmldsig-more#rsa-sha384'
        //    'http://www.w3.org/2001/04/xmldsig-more#rsa-sha512'
        'signatureAlgorithm' => 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
    ),

    // Contact information template, it is recommended to suply a technical and support contacts
    'contactPerson' => array (
        'technical' => array (
            'givenName' => 'xxxxxxx',
            'emailAddress' => 'xxxx@xxxx.xxxx'
        ),
        'support' => array (
            'givenName' => 'xxxxxx',
            'emailAddress' => 'xxxx@xxxx.xxxxxxx'
        ),
    ),

    // Organization information template, the info in en_US lang is recomended, add more if required
    'organization' => array (
        'en-US' => array(
            'name' => 'testing',
            'displayname' => 'testing',
            'url' => 'http://xxxxxxxxxxxxx'
        ),
    ),
);
```

In logout part, I set the  $retrieveParametersFromServer to true in order to get logout work with ADFS.
`
$auth->processSLO(false, $requestID,true);
`

IDP Logout request:
```
<samlp:LogoutRequest ID="_713f4ff4-d978-4ae5-86ce-3ee96640e020" Version="2.0" IssueInstant="2016-07-21T04:18:51.694Z" Destination="https://xxxxxxx/php-saml/index.php?sls" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" NotOnOrAfter="2016-07-21T04:23:51.694Z" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
	<Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://xxxxxxxxx/adfs/services/trust</Issuer>
	<NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">xxxxxx@xxxxx.xxx</NameID>
	<samlp:SessionIndex>_cafdba98-82d1-462e-9ef1-6b7242fd2942</samlp:SessionIndex>
</samlp:LogoutRequest>
```

SP Logout response:
```
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                  xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                  ID="ONELOGIN_a20fc201e0bdab506e47025250f94b24304302ac"
                  Version="2.0"
                  IssueInstant="2016-07-21T04:20:08Z"
                  Destination="https://xxxxxxxxx/adfs/ls/"
                  InResponseTo="_713f4ff4-d978-4ae5-86ce-3ee96640e020"
                  >
    <saml:Issuer>https://xxxxxxx/php-saml/sp</saml:Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
</samlp:LogoutResponse>

```

Thank you.

**Comment by pitbulk** [comment]
I see that you are using 
```
'logoutRequestSigned' => true,
'logoutResponseSigned' => true,
```
but getting a SignatureVerificationFailedException at ADFS.

Can you record your SAML Message with SAMLTracer, and try to validate it at:
* https://www.samltool.com/validate_logout_req.php
* https://www.samltool.com/validate_logout_res.php

Take care of the the RelayState and the SigAlg values.

**Comment by wintercomic** [comment]
Thank you for your reply.

I got "Signature validation failed. Logout Request rejected" in both logout request(IDP->SP) and response(SP->IDP)...

I try the validation tools with other successful IDP-initiated sign out application, I got the same error.

In IDP-initiated sign out, I can't find any RelayState value, so I fill the value that I find in sign in. is it correct?

**Comment by pitbulk** [comment]
Is ok if there is no RelayState value on the IdP-initiated SLO.

The toolkit will check if there is a [$_GET['Signature']](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutRequest.php#L322) and if exists will validate it.
As you can see, if there is no [$_GET['RelayState']](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutRequest.php#L332) then simply not gonna be part of the generated $signedQuery value, used to validate the signature.

If you had the same error using the online tool I suggest you to review IdP and SP settings, something related to the certificates must be wrong.

**Comment by wintercomic** [comment]
Both IDP and SP signing certificate are self-signed. 

IDP-initiated SLO request:
```
https://adfstesting/php-saml/index.php?sls&SAMLRequest=lVLRatwwEPwVo3dZls%2bnnIXj9shRMKQJNKUPfQmytb4IbMnRyiGfX9lOCA3loG%2fSaHZ2ZrUVqnGY5K07uzn8gOcZMCTN6Zo88n2vD6AVFXnb0gLanpa7vKRFlx90AZyrXJPkF3g0zl6TPM1I0iDO0FgMyoYIZVzQ7Irm%2bc%2bslLmQe5GKQ%2fabJKfYxVgV1sqnECaUjCndY1gfzmx6mujijBmr4TWN1y84IElunEVYtGdvpVNoUFo1AsrQyYfj91sZbchuI8nZ4gSd6Q1Eo3cu3Nt7f%2bwD%2bM%2fWdvzD2us4WJTrVC53mbwLrnMDqas1tt9KLxcpRPBLbFIvsd9S7zS8pNqNytg0HleMReKL6QBZ8DOGim1N6uouijan5Jvzo7owCJ7yFTGa9itVQtQfjlp7QCT%2fafbtX76eF420c2PFNh91tS3QQxSNzGb5rvqx3asrVXQtLQ88bowogJZCaLrveSt0VpSqLSv2j8p38K99rP8A&Signature=kSxP8TZa7Jsbd4BuSla%2bOdNxPZ8RTMA1UmokDoQeVUbhDNtQViLcFrzQdUZOvz6uuWQcCD6EEuk3dt9gI3H7%2bGma2i%2f6tlRXcLa5LhvvS%2fd5U8mKM4tkxxpV2z0Jh7jTgBoCE5%2fZ31hwOd7%2blYNjyImMBBgCTicGxSOPRxvKN8J3SeLIu89kril4CCQGThyl426O4OKVDU8MLnZU51udvxehmfg4dXVLS45Rqk11l45K%2fB7sma07aVRI%2bJhrCUO%2bdxcBGOPZfBPxZv4g30RscLInZJ4xj%2bX16ZkONJtDs6y0p9K5fqHSbyeOp2bu81UR9gZisA%2fnoaafqbYEKz5Zyg%3d%3d&SigAlg=http%3a%2f%2fwww.w3.org%2f2000%2f09%2fxmldsig%23rsa-sha1
```

SP response:
```
https://adfs3dev.domain.dev/adfs/ls/?SAMLResponse=fZLRbsIgFIbv9xRN7ysUW2qJbbLMZTFxmkzjxW4MLVSbtEB66LLHXyVzatZIuIDDf%2F7vcGAOvG0MW%2Bmj7u2HBKMVSO%2B7bRQwd5T5faeY5lADU7yVwGzJts%2FvK0YmmJlOW13qxn%2Fy%2Fo2ryWMPDiA7W2s1ZrJcZP5m%2FbravC3XhwSLMKFEJFEaU1xFpMBVStNhckpxKau4EFER0zGjvexgYGT%2BgBwFAfRyqcByZQcRDmmAk4CQHU4ZmbFw%2BjmWtZBga8Wtcz5Za4AhxEUFUyG%2FJkK3vFaTYeliqAE0ilaXxu905h%2FCuBIzKXhASVEEkSyqIJ2SNIhKMhORDENOxJhN7mLzc8OZu02X31ZkXalHZE4mOGsQmDm6FV%2FTDdtabnvI%2Fyh34RctpLfnTS8fPyw4Ndv2ZSkBfA%2F9ItA947K%2F%2F4P5Dw%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=lEt45agsjFPAHly7Qp7gOmRsTMioN6jSqYxklhEd%2F%2FU6%2FS6BLQYUhJLfHLAew9d4twQ7PiUdjs9XRNBQxXVbdbt0exMUUUGWAM6lp2XKt2fdhF%2BA2zJupuABF8JDGdyhVQGXSZO8ruQ3REpaIN33RiNXgLqJidZFDiL7Cj%2BgcNNGVj5b6O%2B7tpKw5Kg%2BTyUZTuppb4NwPypQPFYrXvIxJ2NQlGccLD9lXNvnRXGSaWrijXyZDUjF0QcjOiySVyOpKtcCo6yGVxazY3IjwAmSDtS9fYYIZ9HxyrsjxcLlMVsbp6o2RFTEdvcLpFLMxVZLfZSkY8pfA%2ByMhXi%2Bt7zvqfk%3D
```

Our IDP self-signed signing certificate:
```
MIIC4jCCAcqgAwIBAgIQU78m2NsNPqxBBhliQ0zh0jANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJBREZTIFNpZ25pbmcgLSBhZGZzM2Rldi5kb21haW4uZGV2MB4XDTE1MTIyNTE4NTYyNloXDTE2MTIyNDE4NTYyNlowLTErMCkGA1UEAxMiQURGUyBTaWduaW5nIC0gYWRmczNkZXYuZG9tYWluLmRldjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPsLfdTjb4rt6UwoHydoir+rg9CDILtMlrERkW35GxJw+lKUJ7z74FuHvdBOAc6Ta1WHNmIGJmWXizw73oPvfGS5Oj55xDcJkd9XkIVzCAkjSMqWKjD7F073P2fmqPgowySb0s26HTk+ovaGLpI0Tp3KbcpKo18tyV7BP8vUIhiUl6KkgLvZVFkntCFxFapw3F4Nv3A9g1OLpmAp51w2UGrvK/dp5x//PGTXQ4OgbtPix6VBpiMxgPI+uTxhHwnB+gvpoVRiecotN6N8AexMPnvhEeKyuG/D6w8TepIey7e/6ADdyyY06c3Ffa3aNfly1hkJYDPasVFapTVXAYakeK8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAkmI13W9gFa7HV8RwepxBWZtRps3Ks0TGaicy4N9vIpq8oAaC+ODqTTvzXXGlvuwy88+WeHHAel172Xx8Mk3QoskZ2rV6Sk4SzCMxolXzYjJDqODV+nbmgP7bmyjwyERiarOm6/m/l0saRl+EH8zNkeeO7hzPL99+Rtv4z/l5C1x0RijZIOxA/nQmqTCNIdkwo2HhYKBhLLUaWHWvEe34V4aqVC2ouu9/1of9mEwLdzvxlIu4Vr7ueJqEeWgm6bGpwfzn2AWEF0gYbmLCSRO21VivNvVK7qRoB0mn+3Vx4nUQNffgF49VuG3MnvlR+djFnlzFbQU8yavIQolin5jpQw==
```

SP self-signed certificate:
```
MIIDXzCCAkagAwIBAgIBADANBgkqhkiG9w0BAQ0FADBJMQswCQYDVQQGEwJoazES
MBAGA1UECAwJSG9uZyBLb25nMRAwDgYDVQQKDAd0ZXN0aW5nMRQwEgYDVQQDDAth
ZGZzdGVzdGluZzAeFw0xNjA3MjIwOTE4MzdaFw0xNzA3MjIwOTE4MzdaMEkxCzAJ
BgNVBAYTAmhrMRIwEAYDVQQIDAlIb25nIEtvbmcxEDAOBgNVBAoMB3Rlc3Rpbmcx
FDASBgNVBAMMC2FkZnN0ZXN0aW5nMIIBIzANBgkqhkiG9w0BAQEFAAOCARAAMIIB
CwKCAQIAz8V7Lh0tTbSE93uGwWdAPIZyjzqodlS/3NuPCpd4Iam9dkbaejuZI2aW
2WjnCgZBq+kJwte0Sphel9gP6Gz1HqUPIaD85hRReXgGsBtu7YW7Bk992kEkip4+
mOPn0UxFqDYVIZmQZPYcKZDJwbM6zupqz2I0cdqq13gyxCeoR2FuqOe2MGbqj6lB
4TvwVF0tfKmo11QBZ5YMKnnDWVBv++ytbUNeW9vzmRj9zonePzrEtvmhcIUG1EMq
UaNFs1/mFea3pou2VVxDfu/hJP7bTE50CGDAwvsPPuzlhDdWEctdjJCwEUOa7d14
KcgyjAoybN388Ax/6V03gFRdYCMkPBkCAwEAAaNQME4wHQYDVR0OBBYEFJoaHkBf
YShhE8pz/DsQdJIdJVa0MB8GA1UdIwQYMBaAFJoaHkBfYShhE8pz/DsQdJIdJVa0
MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQENBQADggECADBhb8Ua6hGC8bljpuYY
9g9vzraeyRYlTA5QjEs62Y2+EGwDjBOht6HNrqiatC/EqxRxZ8BocI9WYmVo4a0p
Cdj6mKZLAFqctbIzm0Df5yKsj7e31QWkBi/m0ZzCXAX4oUUulBryVsZfLRTPmBtn
VmJXFlCUbqIEENs+Zj12i6rOUA6HVu43la8aVtKirQELPb3m380S2v7EyVu5Yzjp
FOinbYBxByI1CUIK3akVio1Roidgc/Ulau6yAO03EnSqEisK50w3y4EIuM7BmCva
Cc9LthJfD2z3pQhEtQng0GnmAE+3HBwazxKzLJ9VXYlJ7qe5NLHz4aX8cWXoX9GI
Jn73
```

**Comment by pitbulk** [comment]
Can you test with this patch:
https://github.com/onelogin/php-saml/commit/1bb192d536b25e203d6a07bb884f24da3b607c63

**Comment by wintercomic** [comment]
I try and still receive "SAML Message has wrong signature" in ADFS.

**Comment by pitbulk** [comment]
In the python toolkit we recently fixed an issue related with ADFS and how it Url-Encodes:
https://github.com/onelogin/python-saml/pull/144

Maybe we are experiencing the same issue here?. At php-saml we also build [request](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L478) and [response](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L511) signatures with [urlencode](http://php.net/manual/es/function.urlencode.php) php method, can you replace and use [rawurlencode](http://php.net/manual/es/function.rawurlencode.php) and check if that solves the issue?

**Comment by wintercomic** [comment]
I replace the code with rawurlencode method. IdP-initiated SLO is working!!

Line 478:
```
$msg = 'SAMLRequest='.rawurlencode($samlRequest);
$msg .= '&RelayState='.rawurlencode($relayState);
$msg .= '&SigAlg=' . rawurlencode($signAlgorithm);
```

Line 511:
```
$msg = 'SAMLResponse='.rawurlencode($samlResponse);
if (isset($relayState)) {
            $msg .= '&RelayState='.rawurlencode($relayState);
        }
$msg .= '&SigAlg=' . rawurlencode($signAlgorithm);
```

Now Both SSO, SP-initiated SLO and IDP-initiated SLO work fine.

Thank you very much for your help.

**Comment by pitbulk** [comment]
Ok, I will implement then a solution for that in the same way I did for the python solution.

Thanks for be testing and debugging all the process. We finally found the reason :)
