### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by dipiana** [onelogin/php-saml#424]
We first tested our php-saml integration with a test instance of Azure, where the SLO worked just fine. Now we wanted to use the production idP (AD FS 2016) but the logout stopped working.
It shows an error page on the IdP page.
The logs show the following message:

```
Microsoft.IdentityServer.Protocols.Saml.SamlProtocolSignatureVerificationException: MSIS7084: SAML logout request and logout response messages must be signed when using SAML HTTP Redirect or HTTP POST binding.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolManager.ValidateSignatureRequirements(SamlMessage samlMessage)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolManager.Logout(HttpSamlMessage logoutMessage, String sessionState, String logoutState, Boolean partialLogout, Boolean isUrlTranslationNeeded, HttpSamlMessage& newLogoutMessage, String& newSessionState, String& newLogoutState, Boolean& validLogoutRequest)
```

![image](https://user-images.githubusercontent.com/7633078/72827703-9237dd00-3c7b-11ea-8107-b60e4063969e.png)

Thanks!

**Comment by pitbulk** [comment]
For some reason, ADFS is rejecting your LogoutRequest.

There are some possible causes:
- ADFS expects the LogoutRequest to be signed.
- LogoutRequest signature was made with the wrong sign algorithm
- LogoutRequest signature was with a different private key/public cert pair than the one registered on ADFS.

You may review deeper ADFS logs and determine the cause.
